var constants = {
  FILE_CREATE:                'FILE_CREATE',
  FILE_LOAD:                  'FILE_LOAD',
  FILE_SAVE:                  'FILE_SAVE',
  TAB_SELECT:                 'TAB_SELECT',
  TOOL_SELECT:                'TOOL_SELECT',
  SETTINGS_PAINT:             'SETTINGS_PAINT',
  SETTINGS_GRID:              'SETTINGS_GRID',
  ZOOM_SELECT:                'ZOOM_SELECT',
  BACKGROUND_SELECT:          'BACKGROUND_SELECT',
  FRAME_SELECT:               'FRAME_SELECT',
  MODAL_SHOW:                 'MODAL_SHOW',
  MODAL_HIDE:                 'MODAL_HIDE',
  BRIGHTNESSTOOL_MODE:        'BRIGHTNESSTOOL_MODE',
  BRIGHTNESSTOOL_INTENSITY:   'BRIGHTNESSTOOL_INTENSITY',
  CURSOR_SET:                 'CURSOR_SET',
  COLOR_BRUSH:                'COLOR_BRUSH',
};