var constants = {
  FILE_CREATE:      'FILE_CREATE',
  FILE_LOAD:        'FILE_LOAD',
  FILE_SAVE:        'FILE_SAVE',

  TAB_SELECT:       'TAB_SELECT',
  TOOL_SELECT:      'TOOL_SELECT',
  SETTINGS_PAINT:   'SETTINGS_PAINT',
  SETTINGS_GRID:    'SETTINGS_GRID',

  FRAME_SELECT:     'FRAME_SELECT',

  MODAL_SHOW:       'MODAL_SHOW',
  MODAL_HIDE:       'MODAL_HIDE',
};