export const brightnessToolIntensity = (intensity) => ({ type: "BRIGHTNESSTOOL_INTENSITY", intensity });
export const brightnessToolMode = (mode)  => ({ type: "BRIGHTNESSTOOL_MODE", mode });
export const foldBox = (box) => ({ type: "FOLD_BOX", box });
export const frameSelect = (frame) => ({ type: "FRAME_SELECT", frame });
export const layerAdd = (frame, layer) => ({ type: "LAYER_ADD", frame, layer });
export const layerName = (layer, name) => ({ type: "LAYER_NAME", layer, name });
export const layerSelect = (layer) => ({ type: "LAYER_SELECT", layer });
export const layerOpacity = (layer, opacity) => ({ type: "LAYER_OPACITY", layer, opacity });
export const layerVisibility = (layer, visible) => ({ type: "LAYER_VISIBILITY", layer, visible });
export const selectTool = (tool) => ({ type: "SELECT_TOOL", tool });
export const selectZoom = (zoom) => ({ type: "SELECT_ZOOM", zoom });
export const toggleGrid = () => ({ type: "TOGGLE_GRID" });
export const toggleOnion = () => ({ type: "TOGGLE_ONION" });
export const zoomIn = () => ({ type: "ZOOM_IN" });
export const zoomOut = () => ({ type: "ZOOM_OUT" });
export const zoomFit = (fileSize) => ({ type: "ZOOM_FIT", fileSize });
